version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book
    environment:
      - PORT=${PORT:-3000}
    ports:
      - "${BOOKSERVICE_LOCAL_PORT}:${BOOKSERVICE_DOCKER_PORT}"
